CREATE TABLE 'users'(
  'id' int(11) NOT NULL,
  'first_name' VARCHAR(100)DEFAULT NULL,
  'last_name' VARCHAR(100)DEFAULT NULL,
  'email' VARCHAR(100)DEFAULT NULL,
  'phone' VARCHAR(100)DEFAULT NULL,
  )ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;